// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA2TqGymxiPvarWSOY60L7U1Jx8cLt1sLA',
    appId: '1:713411697629:web:6f915eb366c58c76cef434',
    messagingSenderId: '713411697629',
    projectId: 'tour-guide-a65e8',
    authDomain: 'tour-guide-a65e8.firebaseapp.com',
    storageBucket: 'tour-guide-a65e8.appspot.com',
    measurementId: 'G-2JBZWHPP9G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAJa0q6GTDJ-ObQtovBpRDwDQaIAWlgn7s',
    appId: '1:713411697629:android:6b4813a7c8b7842ccef434',
    messagingSenderId: '713411697629',
    projectId: 'tour-guide-a65e8',
    storageBucket: 'tour-guide-a65e8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAyfv1PA4yB0Cpd2odjVjD9UrcGNANghB8',
    appId: '1:713411697629:ios:e2f61c7e72ce1cb1cef434',
    messagingSenderId: '713411697629',
    projectId: 'tour-guide-a65e8',
    storageBucket: 'tour-guide-a65e8.appspot.com',
    iosClientId: '713411697629-tcfm8s5jqo58ko3ra9sblrauhvhgdf8u.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAyfv1PA4yB0Cpd2odjVjD9UrcGNANghB8',
    appId: '1:713411697629:ios:e2f61c7e72ce1cb1cef434',
    messagingSenderId: '713411697629',
    projectId: 'tour-guide-a65e8',
    storageBucket: 'tour-guide-a65e8.appspot.com',
    iosClientId: '713411697629-tcfm8s5jqo58ko3ra9sblrauhvhgdf8u.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatapp',
  );
}
